// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.example.wall_planar.R$drawable`
class R$drawable extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<R$drawable> $type;

  @jni$_.internal
  R$drawable.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/R$drawable',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$drawable?> nullableType =
      $R$drawable$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$drawable> type = $R$drawable$Type$();
  static final _id_launch_background = _class.staticFieldId(
    r'launch_background',
    r'I',
  );

  /// from: `static public int launch_background`
  static int get launch_background =>
      _id_launch_background.get(_class, const jni$_.jintType());

  /// from: `static public int launch_background`
  static set launch_background(int value) =>
      _id_launch_background.set(_class, const jni$_.jintType(), value);
}

final class $R$drawable$NullableType$ extends jni$_.JType<R$drawable?> {
  @jni$_.internal
  const $R$drawable$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$drawable;';

  @jni$_.internal
  @core$_.override
  R$drawable? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : R$drawable.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$drawable?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$drawable$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$drawable$NullableType$) &&
        other is $R$drawable$NullableType$;
  }
}

final class $R$drawable$Type$ extends jni$_.JType<R$drawable> {
  @jni$_.internal
  const $R$drawable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$drawable;';

  @jni$_.internal
  @core$_.override
  R$drawable fromReference(jni$_.JReference reference) =>
      R$drawable.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$drawable?> get nullableType =>
      const $R$drawable$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$drawable$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$drawable$Type$) &&
        other is $R$drawable$Type$;
  }
}

/// from: `com.example.wall_planar.R$mipmap`
class R$mipmap extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<R$mipmap> $type;

  @jni$_.internal
  R$mipmap.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/R$mipmap',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$mipmap?> nullableType = $R$mipmap$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$mipmap> type = $R$mipmap$Type$();
  static final _id_ic_launcher = _class.staticFieldId(r'ic_launcher', r'I');

  /// from: `static public int ic_launcher`
  static int get ic_launcher =>
      _id_ic_launcher.get(_class, const jni$_.jintType());

  /// from: `static public int ic_launcher`
  static set ic_launcher(int value) =>
      _id_ic_launcher.set(_class, const jni$_.jintType(), value);
}

final class $R$mipmap$NullableType$ extends jni$_.JType<R$mipmap?> {
  @jni$_.internal
  const $R$mipmap$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$mipmap;';

  @jni$_.internal
  @core$_.override
  R$mipmap? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : R$mipmap.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$mipmap?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$mipmap$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$mipmap$NullableType$) &&
        other is $R$mipmap$NullableType$;
  }
}

final class $R$mipmap$Type$ extends jni$_.JType<R$mipmap> {
  @jni$_.internal
  const $R$mipmap$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$mipmap;';

  @jni$_.internal
  @core$_.override
  R$mipmap fromReference(jni$_.JReference reference) =>
      R$mipmap.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$mipmap?> get nullableType => const $R$mipmap$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$mipmap$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$mipmap$Type$) && other is $R$mipmap$Type$;
  }
}

/// from: `com.example.wall_planar.R$style`
class R$style extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<R$style> $type;

  @jni$_.internal
  R$style.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/R$style',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$style?> nullableType = $R$style$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$style> type = $R$style$Type$();
  static final _id_LaunchTheme = _class.staticFieldId(r'LaunchTheme', r'I');

  /// from: `static public int LaunchTheme`
  static int get LaunchTheme =>
      _id_LaunchTheme.get(_class, const jni$_.jintType());

  /// from: `static public int LaunchTheme`
  static set LaunchTheme(int value) =>
      _id_LaunchTheme.set(_class, const jni$_.jintType(), value);

  static final _id_NormalTheme = _class.staticFieldId(r'NormalTheme', r'I');

  /// from: `static public int NormalTheme`
  static int get NormalTheme =>
      _id_NormalTheme.get(_class, const jni$_.jintType());

  /// from: `static public int NormalTheme`
  static set NormalTheme(int value) =>
      _id_NormalTheme.set(_class, const jni$_.jintType(), value);
}

final class $R$style$NullableType$ extends jni$_.JType<R$style?> {
  @jni$_.internal
  const $R$style$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$style;';

  @jni$_.internal
  @core$_.override
  R$style? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : R$style.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$style?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$style$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$style$NullableType$) &&
        other is $R$style$NullableType$;
  }
}

final class $R$style$Type$ extends jni$_.JType<R$style> {
  @jni$_.internal
  const $R$style$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$style;';

  @jni$_.internal
  @core$_.override
  R$style fromReference(jni$_.JReference reference) =>
      R$style.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$style?> get nullableType => const $R$style$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$style$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$style$Type$) && other is $R$style$Type$;
  }
}

/// from: `com.example.wall_planar.R`
class R extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<R> $type;

  @jni$_.internal
  R.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'com/example/wall_planar/R');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R?> nullableType = $R$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R> type = $R$Type$();
}

final class $R$NullableType$ extends jni$_.JType<R?> {
  @jni$_.internal
  const $R$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R;';

  @jni$_.internal
  @core$_.override
  R? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : R.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$NullableType$) && other is $R$NullableType$;
  }
}

final class $R$Type$ extends jni$_.JType<R> {
  @jni$_.internal
  const $R$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R;';

  @jni$_.internal
  @core$_.override
  R fromReference(jni$_.JReference reference) => R.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R?> get nullableType => const $R$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$Type$) && other is $R$Type$;
  }
}

/// from: `com.example.wall_planar.MainActivity`
class MainActivity extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<MainActivity> $type;

  @jni$_.internal
  MainActivity.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/MainActivity',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MainActivity?> nullableType =
      $MainActivity$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MainActivity> type = $MainActivity$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory MainActivity() {
    return MainActivity.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }
}

final class $MainActivity$NullableType$ extends jni$_.JType<MainActivity?> {
  @jni$_.internal
  const $MainActivity$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/MainActivity;';

  @jni$_.internal
  @core$_.override
  MainActivity? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : MainActivity.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<MainActivity?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($MainActivity$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($MainActivity$NullableType$) &&
        other is $MainActivity$NullableType$;
  }
}

final class $MainActivity$Type$ extends jni$_.JType<MainActivity> {
  @jni$_.internal
  const $MainActivity$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/MainActivity;';

  @jni$_.internal
  @core$_.override
  MainActivity fromReference(jni$_.JReference reference) =>
      MainActivity.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<MainActivity?> get nullableType =>
      const $MainActivity$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($MainActivity$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($MainActivity$Type$) &&
        other is $MainActivity$Type$;
  }
}

/// from: `com.example.wall_planar.MeasureUtils`
class MeasureUtils extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<MeasureUtils> $type;

  @jni$_.internal
  MeasureUtils.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/MeasureUtils',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MeasureUtils?> nullableType =
      $MeasureUtils$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MeasureUtils> type = $MeasureUtils$Type$();
  static final _id_startRotationStream = _class.staticMethodId(
    r'startRotationStream',
    r'()V',
  );

  static final _startRotationStream =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public void startRotationStream()`
  static void startRotationStream() {
    _startRotationStream(
      _class.reference.pointer,
      _id_startRotationStream as jni$_.JMethodIDPtr,
    ).check();
  }

  static final _id_startProximityStream = _class.staticMethodId(
    r'startProximityStream',
    r'()V',
  );

  static final _startProximityStream =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public void startProximityStream()`
  static void startProximityStream() {
    _startProximityStream(
      _class.reference.pointer,
      _id_startProximityStream as jni$_.JMethodIDPtr,
    ).check();
  }
}

final class $MeasureUtils$NullableType$ extends jni$_.JType<MeasureUtils?> {
  @jni$_.internal
  const $MeasureUtils$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/MeasureUtils;';

  @jni$_.internal
  @core$_.override
  MeasureUtils? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : MeasureUtils.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<MeasureUtils?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($MeasureUtils$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($MeasureUtils$NullableType$) &&
        other is $MeasureUtils$NullableType$;
  }
}

final class $MeasureUtils$Type$ extends jni$_.JType<MeasureUtils> {
  @jni$_.internal
  const $MeasureUtils$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/MeasureUtils;';

  @jni$_.internal
  @core$_.override
  MeasureUtils fromReference(jni$_.JReference reference) =>
      MeasureUtils.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<MeasureUtils?> get nullableType =>
      const $MeasureUtils$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($MeasureUtils$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($MeasureUtils$Type$) &&
        other is $MeasureUtils$Type$;
  }
}
