// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.example.wall_planar.R$drawable`
class R$drawable extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<R$drawable> $type;

  @jni$_.internal
  R$drawable.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/R$drawable',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$drawable?> nullableType =
      $R$drawable$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$drawable> type = $R$drawable$Type$();
  static final _id_launch_background = _class.staticFieldId(
    r'launch_background',
    r'I',
  );

  /// from: `static public int launch_background`
  static int get launch_background =>
      _id_launch_background.get(_class, const jni$_.jintType());

  /// from: `static public int launch_background`
  static set launch_background(int value) =>
      _id_launch_background.set(_class, const jni$_.jintType(), value);
}

final class $R$drawable$NullableType$ extends jni$_.JType<R$drawable?> {
  @jni$_.internal
  const $R$drawable$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$drawable;';

  @jni$_.internal
  @core$_.override
  R$drawable? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : R$drawable.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$drawable?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$drawable$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$drawable$NullableType$) &&
        other is $R$drawable$NullableType$;
  }
}

final class $R$drawable$Type$ extends jni$_.JType<R$drawable> {
  @jni$_.internal
  const $R$drawable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$drawable;';

  @jni$_.internal
  @core$_.override
  R$drawable fromReference(jni$_.JReference reference) =>
      R$drawable.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$drawable?> get nullableType =>
      const $R$drawable$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$drawable$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$drawable$Type$) &&
        other is $R$drawable$Type$;
  }
}

/// from: `com.example.wall_planar.R$mipmap`
class R$mipmap extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<R$mipmap> $type;

  @jni$_.internal
  R$mipmap.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/R$mipmap',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$mipmap?> nullableType = $R$mipmap$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$mipmap> type = $R$mipmap$Type$();
  static final _id_ic_launcher = _class.staticFieldId(r'ic_launcher', r'I');

  /// from: `static public int ic_launcher`
  static int get ic_launcher =>
      _id_ic_launcher.get(_class, const jni$_.jintType());

  /// from: `static public int ic_launcher`
  static set ic_launcher(int value) =>
      _id_ic_launcher.set(_class, const jni$_.jintType(), value);
}

final class $R$mipmap$NullableType$ extends jni$_.JType<R$mipmap?> {
  @jni$_.internal
  const $R$mipmap$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$mipmap;';

  @jni$_.internal
  @core$_.override
  R$mipmap? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : R$mipmap.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$mipmap?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$mipmap$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$mipmap$NullableType$) &&
        other is $R$mipmap$NullableType$;
  }
}

final class $R$mipmap$Type$ extends jni$_.JType<R$mipmap> {
  @jni$_.internal
  const $R$mipmap$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$mipmap;';

  @jni$_.internal
  @core$_.override
  R$mipmap fromReference(jni$_.JReference reference) =>
      R$mipmap.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$mipmap?> get nullableType => const $R$mipmap$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$mipmap$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$mipmap$Type$) && other is $R$mipmap$Type$;
  }
}

/// from: `com.example.wall_planar.R$style`
class R$style extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<R$style> $type;

  @jni$_.internal
  R$style.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/R$style',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$style?> nullableType = $R$style$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R$style> type = $R$style$Type$();
  static final _id_LaunchTheme = _class.staticFieldId(r'LaunchTheme', r'I');

  /// from: `static public int LaunchTheme`
  static int get LaunchTheme =>
      _id_LaunchTheme.get(_class, const jni$_.jintType());

  /// from: `static public int LaunchTheme`
  static set LaunchTheme(int value) =>
      _id_LaunchTheme.set(_class, const jni$_.jintType(), value);

  static final _id_NormalTheme = _class.staticFieldId(r'NormalTheme', r'I');

  /// from: `static public int NormalTheme`
  static int get NormalTheme =>
      _id_NormalTheme.get(_class, const jni$_.jintType());

  /// from: `static public int NormalTheme`
  static set NormalTheme(int value) =>
      _id_NormalTheme.set(_class, const jni$_.jintType(), value);
}

final class $R$style$NullableType$ extends jni$_.JType<R$style?> {
  @jni$_.internal
  const $R$style$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$style;';

  @jni$_.internal
  @core$_.override
  R$style? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : R$style.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$style?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$style$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$style$NullableType$) &&
        other is $R$style$NullableType$;
  }
}

final class $R$style$Type$ extends jni$_.JType<R$style> {
  @jni$_.internal
  const $R$style$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R$style;';

  @jni$_.internal
  @core$_.override
  R$style fromReference(jni$_.JReference reference) =>
      R$style.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R$style?> get nullableType => const $R$style$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$style$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$style$Type$) && other is $R$style$Type$;
  }
}

/// from: `com.example.wall_planar.R`
class R extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<R> $type;

  @jni$_.internal
  R.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(r'com/example/wall_planar/R');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R?> nullableType = $R$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<R> type = $R$Type$();
}

final class $R$NullableType$ extends jni$_.JType<R?> {
  @jni$_.internal
  const $R$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R;';

  @jni$_.internal
  @core$_.override
  R? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : R.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$NullableType$) && other is $R$NullableType$;
  }
}

final class $R$Type$ extends jni$_.JType<R> {
  @jni$_.internal
  const $R$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/R;';

  @jni$_.internal
  @core$_.override
  R fromReference(jni$_.JReference reference) => R.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<R?> get nullableType => const $R$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($R$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($R$Type$) && other is $R$Type$;
  }
}

/// from: `com.example.wall_planar.AccelerometerUnitsListener`
///
/// Manages the TYPE_ACCELEROMETER data stream, used for the slide measure mode.
class AccelerometerUnitsListener extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<AccelerometerUnitsListener> $type;

  @jni$_.internal
  AccelerometerUnitsListener.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/AccelerometerUnitsListener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AccelerometerUnitsListener?> nullableType =
      $AccelerometerUnitsListener$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AccelerometerUnitsListener> type =
      $AccelerometerUnitsListener$Type$();
  static final _id_ACCELEROMETER_UNITS_CHANNEL = _class.staticFieldId(
    r'ACCELEROMETER_UNITS_CHANNEL',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String ACCELEROMETER_UNITS_CHANNEL`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get ACCELEROMETER_UNITS_CHANNEL =>
      _id_ACCELEROMETER_UNITS_CHANNEL.get(
        _class,
        const jni$_.$JString$NullableType$(),
      );

  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory AccelerometerUnitsListener(jni$_.JObject? context) {
    final _$context = context?.reference ?? jni$_.jNullReference;
    return AccelerometerUnitsListener.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
      ).reference,
    );
  }

  static final _id_onListen = _class.instanceMethodId(
    r'onListen',
    r'(Ljava/lang/Object;Lio/flutter/plugin/common/EventChannel$EventSink;)V',
  );

  static final _onListen =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onListen(java.lang.Object arguments, io.flutter.plugin.common.EventChannel$EventSink events)`
  void onListen(jni$_.JObject? arguments, jni$_.JObject? events) {
    final _$arguments = arguments?.reference ?? jni$_.jNullReference;
    final _$events = events?.reference ?? jni$_.jNullReference;
    _onListen(
      reference.pointer,
      _id_onListen as jni$_.JMethodIDPtr,
      _$arguments.pointer,
      _$events.pointer,
    ).check();
  }

  static final _id_onCancel = _class.instanceMethodId(
    r'onCancel',
    r'(Ljava/lang/Object;)V',
  );

  static final _onCancel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onCancel(java.lang.Object arguments)`
  void onCancel(jni$_.JObject? arguments) {
    final _$arguments = arguments?.reference ?? jni$_.jNullReference;
    _onCancel(
      reference.pointer,
      _id_onCancel as jni$_.JMethodIDPtr,
      _$arguments.pointer,
    ).check();
  }

  static final _id_onSensorChanged = _class.instanceMethodId(
    r'onSensorChanged',
    r'(Landroid/hardware/SensorEvent;)V',
  );

  static final _onSensorChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onSensorChanged(android.hardware.SensorEvent event)`
  void onSensorChanged(jni$_.JObject? event) {
    final _$event = event?.reference ?? jni$_.jNullReference;
    _onSensorChanged(
      reference.pointer,
      _id_onSensorChanged as jni$_.JMethodIDPtr,
      _$event.pointer,
    ).check();
  }

  static final _id_onAccuracyChanged = _class.instanceMethodId(
    r'onAccuracyChanged',
    r'(Landroid/hardware/Sensor;I)V',
  );

  static final _onAccuracyChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public void onAccuracyChanged(android.hardware.Sensor sensor, int accuracy)`
  void onAccuracyChanged(jni$_.JObject? sensor, int accuracy) {
    final _$sensor = sensor?.reference ?? jni$_.jNullReference;
    _onAccuracyChanged(
      reference.pointer,
      _id_onAccuracyChanged as jni$_.JMethodIDPtr,
      _$sensor.pointer,
      accuracy,
    ).check();
  }
}

final class $AccelerometerUnitsListener$NullableType$
    extends jni$_.JType<AccelerometerUnitsListener?> {
  @jni$_.internal
  const $AccelerometerUnitsListener$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/wall_planar/AccelerometerUnitsListener;';

  @jni$_.internal
  @core$_.override
  AccelerometerUnitsListener? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : AccelerometerUnitsListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<AccelerometerUnitsListener?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($AccelerometerUnitsListener$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($AccelerometerUnitsListener$NullableType$) &&
        other is $AccelerometerUnitsListener$NullableType$;
  }
}

final class $AccelerometerUnitsListener$Type$
    extends jni$_.JType<AccelerometerUnitsListener> {
  @jni$_.internal
  const $AccelerometerUnitsListener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/example/wall_planar/AccelerometerUnitsListener;';

  @jni$_.internal
  @core$_.override
  AccelerometerUnitsListener fromReference(jni$_.JReference reference) =>
      AccelerometerUnitsListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<AccelerometerUnitsListener?> get nullableType =>
      const $AccelerometerUnitsListener$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($AccelerometerUnitsListener$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($AccelerometerUnitsListener$Type$) &&
        other is $AccelerometerUnitsListener$Type$;
  }
}

/// from: `com.example.wall_planar.MainActivity`
class MainActivity extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<MainActivity> $type;

  @jni$_.internal
  MainActivity.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/MainActivity',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MainActivity?> nullableType =
      $MainActivity$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MainActivity> type = $MainActivity$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory MainActivity() {
    return MainActivity.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_configureFlutterEngine = _class.instanceMethodId(
    r'configureFlutterEngine',
    r'(Lio/flutter/embedding/engine/FlutterEngine;)V',
  );

  static final _configureFlutterEngine =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void configureFlutterEngine(io.flutter.embedding.engine.FlutterEngine flutterEngine)`
  void configureFlutterEngine(jni$_.JObject? flutterEngine) {
    final _$flutterEngine = flutterEngine?.reference ?? jni$_.jNullReference;
    _configureFlutterEngine(
      reference.pointer,
      _id_configureFlutterEngine as jni$_.JMethodIDPtr,
      _$flutterEngine.pointer,
    ).check();
  }
}

final class $MainActivity$NullableType$ extends jni$_.JType<MainActivity?> {
  @jni$_.internal
  const $MainActivity$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/MainActivity;';

  @jni$_.internal
  @core$_.override
  MainActivity? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : MainActivity.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<MainActivity?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($MainActivity$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($MainActivity$NullableType$) &&
        other is $MainActivity$NullableType$;
  }
}

final class $MainActivity$Type$ extends jni$_.JType<MainActivity> {
  @jni$_.internal
  const $MainActivity$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/MainActivity;';

  @jni$_.internal
  @core$_.override
  MainActivity fromReference(jni$_.JReference reference) =>
      MainActivity.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<MainActivity?> get nullableType =>
      const $MainActivity$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($MainActivity$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($MainActivity$Type$) &&
        other is $MainActivity$Type$;
  }
}

/// from: `com.example.wall_planar.MeasureUtils`
class MeasureUtils extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<MeasureUtils> $type;

  @jni$_.internal
  MeasureUtils.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/MeasureUtils',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MeasureUtils?> nullableType =
      $MeasureUtils$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<MeasureUtils> type = $MeasureUtils$Type$();
  static final _id_initialize = _class.staticMethodId(
    r'initialize',
    r'(Landroid/content/Context;)V',
  );

  static final _initialize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void initialize(android.content.Context context)`
  static void initialize(jni$_.JObject? context) {
    final _$context = context?.reference ?? jni$_.jNullReference;
    _initialize(
      _class.reference.pointer,
      _id_initialize as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).check();
  }

  static final _id_isSensorAvailable = _class.staticMethodId(
    r'isSensorAvailable',
    r'(I)Z',
  );

  static final _isSensorAvailable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
            )
          >();

  /// from: `static public boolean isSensorAvailable(int sensorType)`
  static bool isSensorAvailable(int sensorType) {
    return _isSensorAvailable(
      _class.reference.pointer,
      _id_isSensorAvailable as jni$_.JMethodIDPtr,
      sensorType,
    ).boolean;
  }

  static final _id_getRotationChannelName = _class.staticMethodId(
    r'getRotationChannelName',
    r'()Ljava/lang/String;',
  );

  static final _getRotationChannelName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public java.lang.String getRotationChannelName()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? getRotationChannelName() {
    return _getRotationChannelName(
      _class.reference.pointer,
      _id_getRotationChannelName as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getProximityChannelName = _class.staticMethodId(
    r'getProximityChannelName',
    r'()Ljava/lang/String;',
  );

  static final _getProximityChannelName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public java.lang.String getProximityChannelName()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? getProximityChannelName() {
    return _getProximityChannelName(
      _class.reference.pointer,
      _id_getProximityChannelName as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }

  static final _id_getAccelerometerUnitsStreamChannelName = _class
      .staticMethodId(
        r'getAccelerometerUnitsStreamChannelName',
        r'()Ljava/lang/String;',
      );

  static final _getAccelerometerUnitsStreamChannelName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `static public java.lang.String getAccelerometerUnitsStreamChannelName()`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? getAccelerometerUnitsStreamChannelName() {
    return _getAccelerometerUnitsStreamChannelName(
      _class.reference.pointer,
      _id_getAccelerometerUnitsStreamChannelName as jni$_.JMethodIDPtr,
    ).object<jni$_.JString?>(const jni$_.$JString$NullableType$());
  }
}

final class $MeasureUtils$NullableType$ extends jni$_.JType<MeasureUtils?> {
  @jni$_.internal
  const $MeasureUtils$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/MeasureUtils;';

  @jni$_.internal
  @core$_.override
  MeasureUtils? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : MeasureUtils.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<MeasureUtils?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($MeasureUtils$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($MeasureUtils$NullableType$) &&
        other is $MeasureUtils$NullableType$;
  }
}

final class $MeasureUtils$Type$ extends jni$_.JType<MeasureUtils> {
  @jni$_.internal
  const $MeasureUtils$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/MeasureUtils;';

  @jni$_.internal
  @core$_.override
  MeasureUtils fromReference(jni$_.JReference reference) =>
      MeasureUtils.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<MeasureUtils?> get nullableType =>
      const $MeasureUtils$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($MeasureUtils$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($MeasureUtils$Type$) &&
        other is $MeasureUtils$Type$;
  }
}

/// from: `com.example.wall_planar.ProximitySensorListener`
///
/// Manages the TYPE_PROXIMITY data stream.
class ProximitySensorListener extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ProximitySensorListener> $type;

  @jni$_.internal
  ProximitySensorListener.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/ProximitySensorListener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ProximitySensorListener?> nullableType =
      $ProximitySensorListener$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ProximitySensorListener> type =
      $ProximitySensorListener$Type$();
  static final _id_PROXIMITY_CHANNEL = _class.staticFieldId(
    r'PROXIMITY_CHANNEL',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PROXIMITY_CHANNEL`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get PROXIMITY_CHANNEL =>
      _id_PROXIMITY_CHANNEL.get(_class, const jni$_.$JString$NullableType$());

  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ProximitySensorListener(jni$_.JObject? context) {
    final _$context = context?.reference ?? jni$_.jNullReference;
    return ProximitySensorListener.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
      ).reference,
    );
  }

  static final _id_onListen = _class.instanceMethodId(
    r'onListen',
    r'(Ljava/lang/Object;Lio/flutter/plugin/common/EventChannel$EventSink;)V',
  );

  static final _onListen =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onListen(java.lang.Object arguments, io.flutter.plugin.common.EventChannel$EventSink events)`
  void onListen(jni$_.JObject? arguments, jni$_.JObject? events) {
    final _$arguments = arguments?.reference ?? jni$_.jNullReference;
    final _$events = events?.reference ?? jni$_.jNullReference;
    _onListen(
      reference.pointer,
      _id_onListen as jni$_.JMethodIDPtr,
      _$arguments.pointer,
      _$events.pointer,
    ).check();
  }

  static final _id_onCancel = _class.instanceMethodId(
    r'onCancel',
    r'(Ljava/lang/Object;)V',
  );

  static final _onCancel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onCancel(java.lang.Object arguments)`
  void onCancel(jni$_.JObject? arguments) {
    final _$arguments = arguments?.reference ?? jni$_.jNullReference;
    _onCancel(
      reference.pointer,
      _id_onCancel as jni$_.JMethodIDPtr,
      _$arguments.pointer,
    ).check();
  }

  static final _id_onSensorChanged = _class.instanceMethodId(
    r'onSensorChanged',
    r'(Landroid/hardware/SensorEvent;)V',
  );

  static final _onSensorChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onSensorChanged(android.hardware.SensorEvent event)`
  void onSensorChanged(jni$_.JObject? event) {
    final _$event = event?.reference ?? jni$_.jNullReference;
    _onSensorChanged(
      reference.pointer,
      _id_onSensorChanged as jni$_.JMethodIDPtr,
      _$event.pointer,
    ).check();
  }

  static final _id_onAccuracyChanged = _class.instanceMethodId(
    r'onAccuracyChanged',
    r'(Landroid/hardware/Sensor;I)V',
  );

  static final _onAccuracyChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public void onAccuracyChanged(android.hardware.Sensor sensor, int accuracy)`
  void onAccuracyChanged(jni$_.JObject? sensor, int accuracy) {
    final _$sensor = sensor?.reference ?? jni$_.jNullReference;
    _onAccuracyChanged(
      reference.pointer,
      _id_onAccuracyChanged as jni$_.JMethodIDPtr,
      _$sensor.pointer,
      accuracy,
    ).check();
  }
}

final class $ProximitySensorListener$NullableType$
    extends jni$_.JType<ProximitySensorListener?> {
  @jni$_.internal
  const $ProximitySensorListener$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/ProximitySensorListener;';

  @jni$_.internal
  @core$_.override
  ProximitySensorListener? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : ProximitySensorListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ProximitySensorListener?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ProximitySensorListener$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ProximitySensorListener$NullableType$) &&
        other is $ProximitySensorListener$NullableType$;
  }
}

final class $ProximitySensorListener$Type$
    extends jni$_.JType<ProximitySensorListener> {
  @jni$_.internal
  const $ProximitySensorListener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/ProximitySensorListener;';

  @jni$_.internal
  @core$_.override
  ProximitySensorListener fromReference(jni$_.JReference reference) =>
      ProximitySensorListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ProximitySensorListener?> get nullableType =>
      const $ProximitySensorListener$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ProximitySensorListener$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ProximitySensorListener$Type$) &&
        other is $ProximitySensorListener$Type$;
  }
}

/// from: `com.example.wall_planar.RotationSensorListener`
///
/// Manages the TYPE_ROTATION_VECTOR sensor stream.
class RotationSensorListener extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<RotationSensorListener> $type;

  @jni$_.internal
  RotationSensorListener.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/RotationSensorListener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<RotationSensorListener?> nullableType =
      $RotationSensorListener$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<RotationSensorListener> type =
      $RotationSensorListener$Type$();
  static final _id_ROTATION_CHANNEL = _class.staticFieldId(
    r'ROTATION_CHANNEL',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String ROTATION_CHANNEL`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get ROTATION_CHANNEL =>
      _id_ROTATION_CHANNEL.get(_class, const jni$_.$JString$NullableType$());

  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory RotationSensorListener(jni$_.JObject? context) {
    final _$context = context?.reference ?? jni$_.jNullReference;
    return RotationSensorListener.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
      ).reference,
    );
  }

  static final _id_onListen = _class.instanceMethodId(
    r'onListen',
    r'(Ljava/lang/Object;Lio/flutter/plugin/common/EventChannel$EventSink;)V',
  );

  static final _onListen =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onListen(java.lang.Object arguments, io.flutter.plugin.common.EventChannel$EventSink events)`
  void onListen(jni$_.JObject? arguments, jni$_.JObject? events) {
    final _$arguments = arguments?.reference ?? jni$_.jNullReference;
    final _$events = events?.reference ?? jni$_.jNullReference;
    _onListen(
      reference.pointer,
      _id_onListen as jni$_.JMethodIDPtr,
      _$arguments.pointer,
      _$events.pointer,
    ).check();
  }

  static final _id_onCancel = _class.instanceMethodId(
    r'onCancel',
    r'(Ljava/lang/Object;)V',
  );

  static final _onCancel =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onCancel(java.lang.Object arguments)`
  void onCancel(jni$_.JObject? arguments) {
    final _$arguments = arguments?.reference ?? jni$_.jNullReference;
    _onCancel(
      reference.pointer,
      _id_onCancel as jni$_.JMethodIDPtr,
      _$arguments.pointer,
    ).check();
  }

  static final _id_onSensorChanged = _class.instanceMethodId(
    r'onSensorChanged',
    r'(Landroid/hardware/SensorEvent;)V',
  );

  static final _onSensorChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void onSensorChanged(android.hardware.SensorEvent event)`
  void onSensorChanged(jni$_.JObject? event) {
    final _$event = event?.reference ?? jni$_.jNullReference;
    _onSensorChanged(
      reference.pointer,
      _id_onSensorChanged as jni$_.JMethodIDPtr,
      _$event.pointer,
    ).check();
  }

  static final _id_onAccuracyChanged = _class.instanceMethodId(
    r'onAccuracyChanged',
    r'(Landroid/hardware/Sensor;I)V',
  );

  static final _onAccuracyChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
            )
          >();

  /// from: `public void onAccuracyChanged(android.hardware.Sensor sensor, int accuracy)`
  void onAccuracyChanged(jni$_.JObject? sensor, int accuracy) {
    final _$sensor = sensor?.reference ?? jni$_.jNullReference;
    _onAccuracyChanged(
      reference.pointer,
      _id_onAccuracyChanged as jni$_.JMethodIDPtr,
      _$sensor.pointer,
      accuracy,
    ).check();
  }
}

final class $RotationSensorListener$NullableType$
    extends jni$_.JType<RotationSensorListener?> {
  @jni$_.internal
  const $RotationSensorListener$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/RotationSensorListener;';

  @jni$_.internal
  @core$_.override
  RotationSensorListener? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : RotationSensorListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<RotationSensorListener?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($RotationSensorListener$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($RotationSensorListener$NullableType$) &&
        other is $RotationSensorListener$NullableType$;
  }
}

final class $RotationSensorListener$Type$
    extends jni$_.JType<RotationSensorListener> {
  @jni$_.internal
  const $RotationSensorListener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/RotationSensorListener;';

  @jni$_.internal
  @core$_.override
  RotationSensorListener fromReference(jni$_.JReference reference) =>
      RotationSensorListener.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<RotationSensorListener?> get nullableType =>
      const $RotationSensorListener$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($RotationSensorListener$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($RotationSensorListener$Type$) &&
        other is $RotationSensorListener$Type$;
  }
}

/// from: `com.example.wall_planar.SensorStreamManager`
///
/// Manages sensor streams.
class SensorStreamManager extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<SensorStreamManager> $type;

  @jni$_.internal
  SensorStreamManager.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'com/example/wall_planar/SensorStreamManager',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SensorStreamManager?> nullableType =
      $SensorStreamManager$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<SensorStreamManager> type =
      $SensorStreamManager$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory SensorStreamManager() {
    return SensorStreamManager.fromReference(
      _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr).reference,
    );
  }

  static final _id_initialize = _class.staticMethodId(
    r'initialize',
    r'(Landroid/content/Context;)V',
  );

  static final _initialize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void initialize(android.content.Context context)`
  ///
  /// Must be called before attempting to access sensor streams.
  static void initialize(jni$_.JObject? context) {
    final _$context = context?.reference ?? jni$_.jNullReference;
    _initialize(
      _class.reference.pointer,
      _id_initialize as jni$_.JMethodIDPtr,
      _$context.pointer,
    ).check();
  }

  static final _id_getSensorStatus = _class.staticMethodId(
    r'getSensorStatus',
    r'(I)Z',
  );

  static final _getSensorStatus =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
            )
          >();

  /// from: `static public boolean getSensorStatus(int sensorType)`
  ///
  /// Checks if a specific sensor type is available on the device.
  static bool getSensorStatus(int sensorType) {
    return _getSensorStatus(
      _class.reference.pointer,
      _id_getSensorStatus as jni$_.JMethodIDPtr,
      sensorType,
    ).boolean;
  }

  static final _id_registerRotationListener = _class.staticMethodId(
    r'registerRotationListener',
    r'(Landroid/hardware/SensorEventListener;)Z',
  );

  static final _registerRotationListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public boolean registerRotationListener(android.hardware.SensorEventListener listener)`
  ///
  /// Registers the provided listener for the TYPE_ROTATION_VECTOR sensor.
  static bool registerRotationListener(jni$_.JObject? listener) {
    final _$listener = listener?.reference ?? jni$_.jNullReference;
    return _registerRotationListener(
      _class.reference.pointer,
      _id_registerRotationListener as jni$_.JMethodIDPtr,
      _$listener.pointer,
    ).boolean;
  }

  static final _id_registerProximityListener = _class.staticMethodId(
    r'registerProximityListener',
    r'(Landroid/hardware/SensorEventListener;)Z',
  );

  static final _registerProximityListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public boolean registerProximityListener(android.hardware.SensorEventListener listener)`
  ///
  /// Registers the provided listener for the TYPE_PROXIMITY sensor.
  static bool registerProximityListener(jni$_.JObject? listener) {
    final _$listener = listener?.reference ?? jni$_.jNullReference;
    return _registerProximityListener(
      _class.reference.pointer,
      _id_registerProximityListener as jni$_.JMethodIDPtr,
      _$listener.pointer,
    ).boolean;
  }

  static final _id_registerAccelerometerListener = _class.staticMethodId(
    r'registerAccelerometerListener',
    r'(Landroid/hardware/SensorEventListener;)Z',
  );

  static final _registerAccelerometerListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public boolean registerAccelerometerListener(android.hardware.SensorEventListener listener)`
  ///
  /// Registers the provided listener for the Accelerometer sensor.
  static bool registerAccelerometerListener(jni$_.JObject? listener) {
    final _$listener = listener?.reference ?? jni$_.jNullReference;
    return _registerAccelerometerListener(
      _class.reference.pointer,
      _id_registerAccelerometerListener as jni$_.JMethodIDPtr,
      _$listener.pointer,
    ).boolean;
  }

  static final _id_unregisterSensorEventListener = _class.staticMethodId(
    r'unregisterSensorEventListener',
    r'(Landroid/hardware/SensorEventListener;)V',
  );

  static final _unregisterSensorEventListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public void unregisterSensorEventListener(android.hardware.SensorEventListener listener)`
  ///
  /// Unregisters the provided SensorEventListener.
  static void unregisterSensorEventListener(jni$_.JObject? listener) {
    final _$listener = listener?.reference ?? jni$_.jNullReference;
    _unregisterSensorEventListener(
      _class.reference.pointer,
      _id_unregisterSensorEventListener as jni$_.JMethodIDPtr,
      _$listener.pointer,
    ).check();
  }
}

final class $SensorStreamManager$NullableType$
    extends jni$_.JType<SensorStreamManager?> {
  @jni$_.internal
  const $SensorStreamManager$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/SensorStreamManager;';

  @jni$_.internal
  @core$_.override
  SensorStreamManager? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : SensorStreamManager.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<SensorStreamManager?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($SensorStreamManager$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($SensorStreamManager$NullableType$) &&
        other is $SensorStreamManager$NullableType$;
  }
}

final class $SensorStreamManager$Type$
    extends jni$_.JType<SensorStreamManager> {
  @jni$_.internal
  const $SensorStreamManager$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wall_planar/SensorStreamManager;';

  @jni$_.internal
  @core$_.override
  SensorStreamManager fromReference(jni$_.JReference reference) =>
      SensorStreamManager.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$NullableType$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<SensorStreamManager?> get nullableType =>
      const $SensorStreamManager$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($SensorStreamManager$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($SensorStreamManager$Type$) &&
        other is $SensorStreamManager$Type$;
  }
}
